---
- name: Ensure WireGuard is installed
  ansible.builtin.package:
    name:
      - wireguard-tools
    state: present

- name: "Generate WireGuard configuration"
  template:
    src: wireguard.conf.j2
    dest: "/etc/wireguard/wg-{{ wg_group }}.conf"
  register: config_result
  when: (wireguard | selectattr('name', 'equalto', wg_group) | map(attribute='nodes') | first | dict2items | selectattr('key', 'equalto', inventory_hostname) | list) | length > 0
  notify: Restart WireGuard service

- name: Ensure WireGuard enabled and running
  ansible.builtin.systemd:
    name: wg-quick@wg-{{ wg_group }}.service
    state: started
    enabled: yes
  when: (wireguard | selectattr('name', 'equalto', wg_group) | map(attribute='nodes') | first | dict2items | selectattr('key', 'equalto', inventory_hostname) | list) | length > 0

- name: Add a cron job
  ansible.builtin.lineinfile:
    path: /etc/crontab
    line: "*/5 * * * * root for i in $(cat /etc/wireguard/wg-*.conf | grep Allowed| cut -d '=' -f 2|cut -d '/' -f 1); do ping -c 1 -w 1 $i ; done"
    state: present
    create: yes
    backup: yes
  notify: Restart cron service